### ISSUE TITLE
Permission denied. 

### ISSUE THREAD

**Issue by a0m0rajab** [tunaitis/contributor-map#2]
While using this workflow, I got a permission-denied issue: 

https://github.com/a0m0rajab/contributors-maps/actions/runs/4839855757/jobs/8625146075

Which I solved it by adding: permission: write-all 
in the workflow

```
name: Create Open sauced Map

on:
  push:
    branches:
      - main # Set a branch to deploy


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Contributor Map
        uses: tunaitis/contributor-map@v1 
        with:
          repository: open-sauced/open-sauced
          output: data/open_sauced.svg
```

Here is the reference. 
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
